CREATE TABLE IF NOT EXISTS settings (
id INT AUTO_INCREMENT PRIMARY KEY,
display_name VARCHAR(120) NOT NULL,
logo_url VARCHAR(255),
theme_json JSON,
features_json JSON,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);